<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>movemaster_driver</name>
  <version>0.1.0</version>
  <description>
    MoveMasterDriver: manejo de los SPARK MAX del Movemaster en Position Control
    (hasta 6, configuración actual 3), conversión rad/rotaciones con reductor,
    lectura de estado y envío de referencias sobre SocketCAN.
  </description>
  <maintainer email="todo@todo.todo">movemaster</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>sparkmax_protocol</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
